### ISSUE TITLE
Custom Header

### ISSUE THREAD

**Issue by faryeyay** [redbtc/node-red-contrib-github-plus#1]
Thanks for this node. It's a helpful one. I was wondering, is it possible to specify a custom header with this node? I don't think so but let me know if it's possible. I'm starting to use Node Red and I want to take advantage of some of the Github API described in [this blog post](https://developer.github.com/changes/2019-04-11-pulls-branches-for-commit/). The request `GET /repos/:owner/:repo/commits/:commit_sha/pulls` requests the header `Accept: application/vnd.github.groot-preview+json` to be set.

**Comment by alexk111** [comment]
@faryeyay Done! Added the Media Type option. Check the version **0.3.0** ;)

**Comment by faryeyay** [comment]
@alexk111 thank you!! Awesome
